# Generated by Django 4.0.1 on 2022-01-15 22:58

import django.core.validators
from django.db import migrations, models
import resource_search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('links', models.TextField()),
                ('rec_type', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('indigenous_author', models.BooleanField(choices=[(None, 'Unknown'), (False, 'No'), (True, 'Yes')], null=True)),
                ('year', models.IntegerField(blank=True, validators=[resource_search.models.less_than_current_year, django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
    ]
