# Generated by Django 4.0.1 on 2022-01-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
