# Generated by Django 4.0.1 on 2022-01-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_search', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(to='resource_search.Tag'),
        ),
    ]
