# Generated by Django 4.0.1 on 2022-01-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_search', '0003_resource_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
