# Generated by Django 4.0.1 on 2022-12-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_search', '0007_alter_resource_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='indigenous_author',
            field=models.BooleanField(blank=True, choices=[(None, 'Unknown'), (False, 'No'), (True, 'Yes')], null=True),
        ),
    ]
