# Generated by Django 4.0.1 on 2022-12-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_search', '0008_alter_resource_indigenous_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
